### ISSUE TITLE
Crash when querying servers with manually configured networking

### ISSUE THREAD

**Issue by ravisorg** [cloudsigma/ansible-cloudsigma#1]
`$ ./ansiblecs.py --refreshdb`

```
Refreshing host database...
Adding [redacted] to inventory...
Traceback (most recent call last):
  File "./ansiblecs.py", line 80, in <module>
    refresh_db()
  File "./ansiblecs.py", line 47, in refresh_db
    ipv4 = server['runtime']['nics'][0]['ip_v4']['uuid']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by miguel-cs** [comment]
Hi @ravisorg, thanks for letting us know about this problem, I'll try to replicate the issue.

Could you please mention which OS are you using and the details of your network configuration?

**Comment by gcbirzan** [comment]
Since the server has no configured IP as far as the system is concerned, it won't be possible to manage it via the API in this way. A simple fix is to just skip those servers, as well as those with no public IP.

**Comment by ravisorg** [comment]
That is an absolutely valid point, of course :)

Ideally I could specify the IP address(es) in meta variables attached to the server.
